/**
 * Represents a financial metric displayed in metric cards throughout the dashboard.
 * Contains the metric value, change indicators, and formatting information.
 * 
 * @interface FinancialMetric
 * @example
 * ```typescript
 * const revenueMetric: FinancialMetric = {
 *   id: 'total-revenue',
 *   title: 'Total Revenue',
 *   value: 1500000,
 *   change: 12.5,
 *   changeType: 'increase',
 *   period: 'vs last month',
 *   format: 'currency'
 * };
 * ```
 */
export interface FinancialMetric {
  /** Unique identifier for the metric */
  id: string;
  
  /** Display title for the metric card */
  title: string;
  
  /** Numeric value of the metric */
  value: number;
  
  /** Percentage change from previous period (positive or negative) */
  change: number;
  
  /** Whether the change represents an increase or decrease */
  changeType: 'increase' | 'decrease';
  
  /** Time period description for the change (e.g., "vs last month") */
  period: string;
  
  /** How the value should be formatted for display */
  format: 'currency' | 'percentage' | 'number';
}

/**
 * Monthly revenue data used for trend charts and financial analysis.
 * Contains revenue, expenses, and calculated net income for a specific month.
 * 
 * @interface RevenueData
 * @example
 * ```typescript
 * const januaryData: RevenueData = {
 *   month: 'Jan 2024',
 *   revenue: 850000,
 *   expenses: 720000,
 *   netIncome: 130000
 * };
 * ```
 */
export interface RevenueData {
  /** Month and year label (e.g., "Jan 2024") */
  month: string;
  
  /** Total revenue for the month in dollars */
  revenue: number;
  
  /** Total expenses for the month in dollars */
  expenses: number;
  
  /** Calculated net income (revenue - expenses) */
  netIncome: number;
}

/**
 * Financial performance data for a specific hospital department.
 * Used in department comparison tables and departmental analysis.
 * 
 * @interface DepartmentFinance
 * @example
 * ```typescript
 * const cardiologyDept: DepartmentFinance = {
 *   department: 'Cardiology',
 *   revenue: 450000,
 *   expenses: 320000,
 *   profit: 130000,
 *   profitMargin: 28.9
 * };
 * ```
 */
export interface DepartmentFinance {
  /** Name of the hospital department */
  department: string;
  
  /** Total revenue generated by the department */
  revenue: number;
  
  /** Total expenses incurred by the department */
  expenses: number;
  
  /** Calculated profit (revenue - expenses) */
  profit: number;
  
  /** Profit margin as a percentage ((profit / revenue) * 100) */
  profitMargin: number;
}

/**
 * Patient statistics and hospital utilization metrics.
 * Provides insights into patient volume, types, and facility utilization.
 * 
 * @interface PatientMetrics
 * @example
 * ```typescript
 * const hospitalMetrics: PatientMetrics = {
 *   totalPatients: 1250,
 *   inpatients: 320,
 *   outpatients: 780,
 *   emergencyVisits: 150,
 *   averageStayDuration: 4.2,
 *   occupancyRate: 85.5
 * };
 * ```
 */
export interface PatientMetrics {
  /** Total number of patients served in the period */
  totalPatients: number;
  
  /** Number of patients admitted for overnight stays */
  inpatients: number;
  
  /** Number of patients treated without admission */
  outpatients: number;
  
  /** Number of emergency department visits */
  emergencyVisits: number;
  
  /** Average length of stay in days for inpatients */
  averageStayDuration: number;
  
  /** Hospital bed occupancy rate as a percentage */
  occupancyRate: number;
}

/**
 * Expense category breakdown for pie chart visualization.
 * Each category includes amount, percentage, and display color.
 * 
 * @interface ExpenseBreakdown
 * @example
 * ```typescript
 * const staffingExpense: ExpenseBreakdown = {
 *   category: 'Staffing',
 *   amount: 850000,
 *   percentage: 45.2,
 *   color: '#a855f7'
 * };
 * ```
 */
export interface ExpenseBreakdown {
  /** Name of the expense category (e.g., 'Staffing', 'Equipment') */
  category: string;
  
  /** Dollar amount spent in this category */
  amount: number;
  
  /** Percentage of total expenses (should sum to 100% across all categories) */
  percentage: number;
  
  /** Hex color code for chart visualization */
  color: string;
}

/**
 * Cash flow data for a specific time period showing different cash flow types.
 * Used for cash flow analysis and financial health monitoring.
 * 
 * @interface CashFlowData
 * @example
 * ```typescript
 * const quarterData: CashFlowData = {
 *   date: 'Q1 2024',
 *   operatingCashFlow: 450000,
 *   investingCashFlow: -150000,
 *   financingCashFlow: 75000,
 *   netCashFlow: 375000
 * };
 * ```
 */
export interface CashFlowData {
  /** Time period label (e.g., 'Q1 2024', 'Jan 2024') */
  date: string;
  
  /** Cash flow from operating activities */
  operatingCashFlow: number;
  
  /** Cash flow from investing activities (often negative) */
  investingCashFlow: number;
  
  /** Cash flow from financing activities */
  financingCashFlow: number;
  
  /** Net cash flow (sum of all cash flows) */
  netCashFlow: number;
}

/**
 * Union type representing different categories of hospitals.
 * Used for filtering and categorizing hospital data.
 * 
 * @type HospitalType
 * @example
 * ```typescript
 * const hospitalCategory: HospitalType = 'Specialty';
 * ```
 */
export type HospitalType = 'General' | 'Specialty' | 'Pediatric' | 'Trauma';

/**
 * Hospital entity representing a healthcare facility in the system.
 * Contains basic identifying information and categorization.
 * 
 * @interface Hospital
 * @example
 * ```typescript
 * const hospital: Hospital = {
 *   id: 'general-001',
 *   name: 'Metro General Hospital',
 *   location: 'Downtown Medical District',
 *   type: 'General'
 * };
 * ```
 */
export interface Hospital {
  /** Unique identifier for the hospital */
  id: string;
  
  /** Full name of the hospital */
  name: string;
  
  /** Geographic location or address description */
  location: string;
  
  /** Category of hospital services offered */
  type: HospitalType;
}

/**
 * Complete dataset for a hospital's financial and operational data for a specific year.
 * This is the main data structure used throughout the dashboard.
 * 
 * @interface HospitalData
 * @example
 * ```typescript
 * const hospitalData: HospitalData = {
 *   hospitalId: 'general-001',
 *   year: 2024,
 *   financialMetrics: [revenueMetric, profitMetric],
 *   revenueData: [jan2024, feb2024, mar2024],
 *   departmentFinances: [cardiologyDept, emergencyDept],
 *   patientMetrics: hospitalMetrics,
 *   expenseBreakdown: [staffingExpense, equipmentExpense],
 *   cashFlowData: [q1Data, q2Data],
 *   lastUpdated: '2024-03-15T10:30:00Z'
 * };
 * ```
 */
export interface HospitalData {
  /** Reference to the hospital this data belongs to */
  hospitalId: string;
  
  /** Year this data represents (e.g., 2024) */
  year: number;
  
  /** Array of key financial metrics for dashboard cards */
  financialMetrics: FinancialMetric[];
  
  /** Monthly revenue, expense, and net income data for trend charts */
  revenueData: RevenueData[];
  
  /** Financial performance data for each department */
  departmentFinances: DepartmentFinance[];
  
  /** Patient volume and facility utilization statistics */
  patientMetrics: PatientMetrics;
  
  /** Categorized expense breakdown for pie charts */
  expenseBreakdown: ExpenseBreakdown[];
  
  /** Quarterly or monthly cash flow analysis data */
  cashFlowData: CashFlowData[];
  
  /** ISO timestamp of when this data was last updated */
  lastUpdated: string;
}

